// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type STStudentCreateReq struct {
	Name   string `json:"name"`
	Age    uint64 `json:"age"`
	Gender uint64 `json:"gender"`
}

type STStudentCreateRsp struct {
	Id uint64 `json:"id"`
}

type STStudentDeleteReq struct {
	Id uint64 `path:"id"`
}

type STStudentDeleteRsp struct {
}

type STStudentUpdateReq struct {
	Id     uint64 `path:"id"`
	Name   string `json:"name"`
	Age    uint64 `json:"age"`
	Gender uint64 `json:"gender"`
}

type STStudentUpdateRsp struct {
}

type STStudentRetrieveyReq struct {
	Id uint64 `path:"id"`
}

type STStudentRetrieveRsp struct {
	Id        uint64 `json:"id"`
	Name      string `json:"name"`
	Age       uint64 `json:"age"`
	Gender    uint64 `json:"gender"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type STStudentListReq struct {
	Page   uint64 `json:"page"`
	Limit  uint64 `json:"limit"`
	Id     uint64 `json:"id"`
	Name   string `json:"name"`
	Age    uint64 `json:"age"`
	Gender uint64 `json:"gender"`
}

type STStudentListRsp struct {
	Total uint64    `json:"total"`
	Items []Student `json:"items"`
}

type Student struct {
	Id        uint64 `json:"id"`
	Name      string `json:"name"`
	Age       uint64 `json:"age"`
	Gender    uint64 `json:"gender"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type STGradeCreateReq struct {
	UserId  uint64  `json:"userId"`
	Chinese float64 `json:"chinese"`
	Math    float64 `json:"math"`
	English float64 `json:"english"`
	Year    uint64  `json:"year"`
	Term    uint64  `json:"term"`
}

type STGradeCreateRsp struct {
	Id uint64 `json:"id"`
}

type STGradeDeleteReq struct {
	Id uint64 `path:"id"`
}

type STGradeDeleteRsp struct {
}

type STGradeUpdateReq struct {
	Id      uint64  `path:"id"`
	UserId  uint64  `json:"userId"`
	Chinese float64 `json:"chinese"`
	Math    float64 `json:"math"`
	English float64 `json:"english"`
	Year    uint64  `json:"year"`
	Term    uint64  `json:"term"`
}

type STGradeUpdateRsp struct {
}

type STGradeListReq struct {
	Page    uint64  `json:"page"`
	Limit   uint64  `json:"limit"`
	Id      uint64  `path:"id"`
	UserId  uint64  `json:"userId"`
	Chinese float64 `json:"chinese"`
	Math    float64 `json:"math"`
	English float64 `json:"english"`
	Year    uint64  `json:"year"`
	Term    uint64  `json:"term"`
}

type STGradeListRsp struct {
	Total uint64  `json:"total"`
	Items []Grade `json:"items"`
}

type STGradeRetrieveyReq struct {
	Id uint64 `path:"id"`
}

type STGradeRetrieveRsp struct {
	Id        uint64  `json:"id"`
	UserId    uint64  `json:"userId"`
	Chinese   float64 `json:"chinese"`
	Math      float64 `json:"math"`
	English   float64 `json:"english"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

type Grade struct {
	Id        uint64  `path:"id"`
	UserId    uint64  `json:"userId"`
	Chinese   float64 `json:"chinese"`
	Math      float64 `json:"math"`
	English   float64 `json:"english"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
	Year      uint64  `json:"year"`
	Term      uint64  `json:"term"`
}

type STStuCreateReq struct {
	Name  string `json:"name"`  // 名称
	StuId string `json:"stuId"` //学号
	Age   uint64 `json:"age"`   // 年龄
	Sex   uint64 `json:"sex"`   // 性别
	Grade uint64 `json:"grade"` //年级
	Step  string `json:"step"`  //所在系
}

type STStuCreateRsp struct {
	Id uint64 `json:"id"`
}

type STStuDeleteReq struct {
	Id uint64 `path:"id"`
}

type STStuDeleteRsp struct {
}

type STStuUpdateReq struct {
	Id    uint64 `path:"id"`
	Name  string `json:"name,optional"`
	StuId string `json:"stuId,optional"`
	Age   uint64 `json:"age,optional"`
	Sex   uint64 `json:"sex,optional"`
	Grade uint64 `json:"grade,optional"`
	Step  string `json:"step,optional"`
}

type STStuUpdateRsp struct {
}

type STStuRetrieveReq struct {
	Id uint64 `path:"id"`
}

type STStuRetrieveRsp struct {
	Id        uint64 `json:"id"`
	Name      string `json:"name"`
	StuId     string `json:"stuId"`
	Age       uint64 `json:"age"`
	Sex       uint64 `json:"sex"`
	Grade     uint64 `json:"grade"`
	Step      string `json:"step"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type STStuListReq struct {
	Page  uint64 `form:"page"`
	Limit uint64 `form:"limit"`
	Id    uint64 `form:"id,optional"`
	Name  string `form:"name,optional"`  // 名称
	StuId string `form:"stuId,optional"` //学号
	Age   uint64 `form:"age,optional"`   // 年龄
	Sex   uint64 `form:"sex,optional"`   // 性别
	Grade uint64 `form:"grade,optional"` //年级
	Step  string `form:"step,optional"`
}

type STStuListRsp struct {
	Total uint64 `json:"total"`
	Items []Stu  `json:"items"`
}

type STResetPassworReq struct {
	StuId      string `json:"stuId"`
	Password   string `json:"password"`
	RePassword string `json:"rePassword"`
}

type STResetPassworRsp struct {
}

type STLoginReq struct {
	StuId    string `json:"stuId"`
	Password string `json:"password"`
}

type STLoginRsp struct {
	Token string `json:"token"`
}

type Stu struct {
	Id        uint64 `path:"id""`
	Name      string `json:"name"`
	StuId     string `json:"stuId"`
	Age       uint64 `json:"age"`
	Sex       uint64 `json:"sex"`
	Grade     uint64 `json:"grade"`
	Step      string `json:"step"`
	CreatedAt int64  `json:"creatAt"`
	UpdatedAt int64  `json:"Update"`
}

type STScoreCreateReq struct {
	Chinese    float64 `json:"chinese"` // 语文
	CTeacherId string  `json:"cTeacherId"`
	Math       float64 `json:"math"` // 数学
	MTeacherId string  `json:"mTeacherId"`
	English    float64 `json:"english"` // 英语
	ETeacherId string  `json:"eTeacherId"`
	StuId      string  `json:"stuId"`
	Year       uint64  `json:"year"` // 年份
	Term       uint64  `json:"term"` // 学期
}

type STScoreCreateRsp struct {
	Id uint64 `json:"id"`
}

type STScoreDeleteReq struct {
	Id uint64 `path:"id"`
}

type STScoreDeleteRsp struct {
}

type STScoreUpdateReq struct {
	Id         uint64  `path:"id"`
	Chinese    float64 `json:"chinese,optional"` // 语文
	CTeacherId string  `json:"cTeacherId,optional"`
	Math       float64 `json:"math,optional"` // 数学
	MTeacherId string  `json:"mTeacherId,optional"`
	English    float64 `json:"english,optional"` // 英语
	ETeacherId string  `json:"eTeacherId,optional"`
	StuId      string  `json:"stuId,optional"`
	Year       uint64  `json:"year,optional"` // 年份
	Term       uint64  `json:"term,optional"` // 学期
}

type STScoreUpdateRsp struct {
}

type STScoreRetrieveReq struct {
	Id uint64 `path:"id"`
}

type STScoreRetrieveRsp struct {
	Id         uint64  `json:"id"`
	Chinese    float64 `json:"chinese"` // 语文
	CTeacherId string  `json:"cTeacherId"`
	Math       float64 `json:"math"` // 数学
	MTeacherId string  `json:"mTeacherId"`
	English    float64 `json:"english"` // 英语
	ETeacherId string  `json:"eTeacherId"`
	StuId      string  `json:"stuId"`
	Year       uint64  `json:"year"` // 年份
	Term       uint64  `json:"term"` // 学期
	CreatedAt  int64   `json:"createdAt"`
	UpdatedAt  int64   `json:"updatedAt"`
}

type STScoreListReq struct {
	Page       uint64  `form:"page"`
	Limit      uint64  `form:"limit"`
	Id         uint64  `form:"id,optional"`
	Chinese    float64 `form:"chinese,optional"` // 语文
	CTeacherId string  `form:"cTeacherId,optional"`
	Math       float64 `form:"math,optional"` // 数学
	MTeacherId string  `form:"mTeacherId,optional"`
	English    float64 `form:"english,optional"` // 英语
	ETeacherId string  `form:"eTeacherId,optional"`
	StuId      string  `form:"stuId,optional"`
	Year       uint64  `form:"year,optional"` // 年份
	Term       uint64  `form:"term,optional"` // 学期
}

type STScoreListRsp struct {
	Total uint64  `json:"total"`
	Items []Score `json:"items"`
}

type Score struct {
	Id         uint64  `json:"id"`
	Chinese    float64 `json:"chinese"` // 语文
	CTeacherId string  `json:"cTeacherId"`
	Math       float64 `json:"math"` // 数学
	MTeacherId string  `json:"mTeacherId"`
	English    float64 `json:"english"` // 英语
	ETeacherId string  `json:"eTeacherId"`
	StuId      string  `json:"stuId"`
	Year       uint64  `json:"year"` // 年份
	Term       uint64  `json:"term"` // 学期
	CreatedAt  int64   `json:"createdAt"`
	UpdatedAt  int64   `json:"updatedAt"`
}

type STTeacherCreateReq struct {
	Name      string `json:"name"`      // 名称
	TeacherId string `json:"teacherId"` //教师编号
	Step      string `json:"step"`      //所在系
	Course    string `json:"course"`
}

type STTeacherCreateRsp struct {
	Id uint64 `json:"id"`
}

type STTeacherDeleteReq struct {
	Id uint64 `path:"id"`
}

type STTeacherDeleteRsp struct {
}

type STTeacherUpdateReq struct {
	Id        uint64 `path:"id"`
	Name      string `json:"name,optional"`      // 名称
	TeacherId string `json:"teacherId,optional"` //教师编号
	Step      string `json:"step,optional"`      //所在系
	Course    string `json:"course,optional"`
}

type STTeacherUpdateRsp struct {
}

type STTeacherRetrieveReq struct {
	Id uint64 `path:"id"`
}

type STTeacherRetrieveRsp struct {
	Id        uint64 `json:"id"`
	Name      string `json:"name"`      // 名称
	TeacherId string `json:"teacherId"` //教师编号
	Step      string `json:"step"`      //所在系
	Course    string `json:"course"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type STTeacherListReq struct {
	Page      uint64 `form:"page"`
	Limit     uint64 `form:"limit"`
	Id        uint64 `form:"id,optional"`
	Name      string `form:"name,optional"`      // 名称
	TeacherId string `form:"teacherId,optional"` //教师编号
	Step      string `form:"step,optional"`      //所在系
	Course    string `form:"course,optional"`
}

type STTeacherListRsp struct {
	Total uint64    `json:"total"`
	Items []Teacher `json:"items"`
}

type Teacher struct {
	Id        uint64 `json:"id"`
	Name      string `json:"name"`      // 名称
	TeacherId string `json:"teacherId"` //教师编号
	Step      string `json:"step"`      //所在系
	Course    string `json:"course"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type TResetPassworReq struct {
	TeacherId  string `json:"teacherId"`
	Password   string `json:"password"`
	RePassword string `json:"rePassword"`
}

type TResetPassworRsp struct {
}

type TLoginReq struct {
	TeacherId string `json:"teacherId"`
	Password  string `json:"password"`
}

type TLoginRsp struct {
	Token string `json:"token"`
}
